name: antarctica_today
channels:
  - conda-forge
  - nodefaults
platforms:
  - linux-64
dependencies:

  # Runtime dependencies
  # --------------------
  - click ~=8.1
  - earthaccess ~=0.6.1
  - gdal ~=3.5
  - pandas ~=1.4
  - geopandas ~=0.14.0
  - cartopy ~=0.21.0
  - python-dateutil ~=2.8
  - pillow ~=9.2

  ## Need a numpy version before np.int was deprecated:
  - numpy ~=1.19.4

  ## Currently, numpy's pin keeps Xarray back at v2022.09
  - xarray
  - netcdf4


  # Development dependencies
  # ------------------------
  - matplotlib-base
  - pre-commit
  - conda-lock
  # - pytest

  # - mypy
  # - types-pillow ~=9.2
