name: antarctica_today
channels:
  - conda-forge
  - nodefaults
platforms:
  - linux-64
dependencies:
  # Runtime dependencies
  - click ~=8.1

  ## Need a numpy version before np.int was deprecated:
  - numpy ~=1.19.4

  # Development dependencies
  - matplotlib-base
  - pre-commit
