[tool.ruff]
target-version = "py38"

# These are all great rulesets, but many aren't passing. Some good ones to
# start with:
#   * RUF: Ruff-specific rules not from other linters
#   * UP: mostly migrates `str.format` -> f-strings
#   * C4: Removes unnecessary comprehenions, other comprehension best practices
#   * A: Prevents shadowing of python built-ins like "all"
select = [
  # "F",  # pyflakes
  # "E",  # pycodestyle warnings
  # "W",  # pycodestyle warnings
  # "C4",  # flake8-comprehensions
  "C90",  # mccabe
  "I",  # isort
  # "N",  # pep8-naming
  # "D",  # pydocstyle
  # "UP",  # pyupgrade
  "YTT",  # flake8-2020
  # "B",  # flake8-bugbear
  # "A",  # flake8-builtins
  "T10",  # flake8-debugger
  # "RUF",  # ruff-specific rules
]

ignore = [
  # D1: Ignore errors requiring docstrings on everything.
  # D203: "1 blank line required before class docstring"
  # D213: "Multi-line docstring summary should start at the second line"
  # E731: Lambda assignments are OK, use your best judgement.
  # RUF010: !a, !r, !s are too magical for me.
  "D1", "D203", "D213", "E731", "RUF010",
]

[tool.ruff.isort]
# known-first-party = ["antarctica_today"]

[tool.ruff.mccabe]
max-complexity = 23
# TODO: lower! Aim for 8?

[tool.ruff.flake8-quotes]
inline-quotes = "double"
